config/routes.rb
Rails.application.routes.draw do
  root :to => 'users#index'
  resources :articles
  resources :users
  scope path: '(:target_model)', shallow_path: '(:target_model)' do
    resources :dynabute_fields, except: [:update, :edit]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_dynabutes
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_dynabutes
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:name, dynabute_values_attributes: [:id, :value, :field_id, :name, :_destroy])
    end
end

app/controllers/dynabute_fields_controller.rb
class DynabuteFieldsController < ApplicationController
  before_action :set_dynabute, only: [:show, :destroy]
  before_action :set_target_model, only: [:index, :new]
  ALLOWED_MODELS = %w(user article)

  # GET /dynabute_fields
  # GET /dynabute_fields.json
  def index
    @dynabute_fields = Dynabute::Field.where(target_model: target_model)
  end

  # GET /dynabute_fields/1
  # GET /dynabute_fields/1.json
  def show
  end

  # GET /dynabute_fields/new
  def new
    @dynabute_field= Dynabute::Field.new(target_model: target_model)
  end

  # POST /dynabute_fields
  # POST /dynabute_fields.json
  def create
    @dynabute_field = Dynabute::Field.new(dynabute_params)

    respond_to do |format|
      if @dynabute_field.save
        format.html { redirect_to dynabute_fields_path(@dynabute_field.target_model), notice: 'Dynabute was successfully created.' }
        format.json { render :show, status: :created, location: @dynabute_field}
      else
        format.html { render :new }
        format.json { render json: @dynabute_field.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dynabute_fields/1
  # DELETE /dynabute_fields/1.json
  def destroy
    @dynabute_field.destroy
    respond_to do |format|
      format.html { redirect_to dynabute_fields_path(@dynabute_field.target_model), notice: 'Dynabute was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_dynabute
      @dynabute_field= Dynabute::Field.find(params[:id])
    end

    def dynabute_params
      params.fetch(:dynabute_field, {}).permit(
        :id,
        :name,
        :target_model,
        :value_type,
        :has_many,
        options_attributes: [:id, :label]
      )
    end

    def target_model
      params[:target_model] && params[:target_model].classify
    end

    def set_target_model
      return render file: "#{Rails.root}/public/404.html", layout: false, status: 404 unless ALLOWED_MODELS.include?(target_model.downcase)
      @target_model = target_model.downcase
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, dynabute_values_attributes: [:id, :value, :field_id, :name, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def dynabute_value_text(value, field)
    return '' if value.blank?
    if field.has_many
      value.map{|v| value_text(v, field) }.join(',')
    else
      value_text(value, field)
    end
  end

  private
  def value_text(value, field)
    field.value_type == 'select' ? value.option.label : value.value
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/dynabutes_helper.rb
module DynabutesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.slim
div#dynabute-form
= javascript_pack_tag 'dynabute_form/form'

javascript:
  $('#dynabute-form').data({
    modelId: #{raw @article.id.to_json.html_safe},
    controllerName: #{raw controller_name.to_json.html_safe}
  });

app/views/articles/edit.html.slim
- model_class = Article
.page-header
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/articles/index.html.slim
- model_class = Article
.page-header
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
  = link_to t('.new', :default => t("helpers.links.new")), new_article_path, :class => 'btn btn-primary'
  = render :partial => "shared/dynabute_value_table", locals: {model_class: model_class, model_attrs: [:name, :created_at], records: @articles}

app/views/articles/new.html.slim
- model_class = Article
.page-header
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/articles/show.html.slim
- model_class = Article
.page-header
  h1=t '.title', :default => model_class.model_name.human.titleize

p
  strong= model_class.human_attribute_name(:name) + ':'
  br
  = @article.name

= link_to t('.back', :default => t("helpers.links.back")), articles_path, :class => 'btn btn-default'
'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_article_path(@article), :class => 'btn btn-default'
'
= link_to t('.destroy', :default => t("helpers.links.destroy")), article_path(@article), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/dynabute_fields/_form.html.slim
= simple_form_for(@dynabute_field)  do |f|
  = f.error_notification
  = f.hidden_field :target_model
  = f.input :name
  #value_type= f.input :value_type, collection: Dynabute::Field::TYPES
  = f.input :has_many

  #options.row[style="margin-bottom: 30px;"]
    .col-lg-offset-1.col-lg-11
      h3 options
      = f.simple_fields_for :options do |option|
        = render 'option_fields', f: option
      .links
        = link_to_add_association 'add option', f, :options, class: 'btn btn-info btn-xs'

  = f.button :submit, class: 'btn-primary'

  javascript:
    const value_type = $('#value_type select'),
          options = $('#options');

    const set_options_visibility = ($elem) => {
      if($elem.val() == 'select'){
        options.show()
      } else {
        options.hide()
      }
    }
    value_type.change(function(){ set_options_visibility($(this)) })
    set_options_visibility(value_type)

app/views/dynabute_fields/_option_fields.html.slim
.row.nested-fields.vertical-middle
  .col-lg-8= f.input :label
  .col-lg-2= link_to_remove_association "remove option", f, class: 'btn btn-danger btn-xs'

app/views/dynabute_fields/index.html.slim
- model_class = Dynabute::Field
.page-header
  h1="Dynabute Fileds for #{@target_model.classify}"
= link_to t('.new', :default => t("helpers.links.new")), new_dynabute_field_path(@target_model), :class => 'btn btn-primary'
table.table.table-striped
  thead
    tr
      th= model_class.human_attribute_name(:name)
      th value_type
      th has_many
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @dynabute_fields.each do |dynabute_field|
      tr
        td = dynabute_field.name
        td = dynabute_field.value_type
        td = dynabute_field.has_many
        td
          = link_to t('.show', :default => t("helpers.links.show")), dynabute_field_path(dynabute_field), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), dynabute_field_path(dynabute_field), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

app/views/dynabute_fields/new.html.slim
- model_class = Dynabute::Field
.page-header
  h1="New Dynabute Field for #{@target_model.classify}"
= render :partial => "form"

app/views/dynabute_fields/show.html.slim
- model_class = Dynabute::Field
.page-header
  h1=t '.title', :default => model_class.model_name.human.titleize

p
  strong= model_class.human_attribute_name(:name) + ':'
  br
  = @dynabute_field.name
p
  strong= model_class.human_attribute_name(:value_type) + ':'
  br
  = @dynabute_field.value_type
p
  strong= model_class.human_attribute_name(:has_many) + ':'
  br
  = @dynabute_field.has_many
p
  strong= model_class.human_attribute_name(:target_model) + ':'
  br
  = @dynabute_field.target_model

= link_to t('.back', :default => t("helpers.links.back")), dynabute_fields_path(@dynabute_field.target_model.downcase), :class => 'btn btn-default'
'
= link_to t('.destroy', :default => t("helpers.links.destroy")), dynabute_field_path(@dynabute_field), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "DynabuteDemo"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag 'application'
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  body
    .navbar.navbar-default.navbar-static-top
        .container
          button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="#"DynabuteDemo
          .navbar-collapse.collapse.navbar-responsive-collapse
            ul.nav.navbar-nav
              li= link_to "Users", "/users"
              li= link_to "Users Dynabutes", "/dynabute_fields?target_model=user"
              li= link_to "Articles", "/articles"
              li= link_to "Article Dynabutes", "/dynabute_fields?target_model=article"
            ul.nav.navbar-nav.navbar-right
              li= link_to "Demo App Source in Github", 'https://github.com/Liooo/dynabute-demo'

    .container
      .row
        .col-lg-12
          = bootstrap_flash
          = yield

      footer
        p &copy; Company 2017

app/views/shared/_dynabute_value_table.html.slim
- model_name = model_class.to_s.downcase
- fields = model_class.dynabutes

table.table.table-striped
  thead
    tr
      - model_attrs.each do |attr|
        th= model_class.human_attribute_name(attr)
      - fields.each do |field|
        th = field.name
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - records.each do |record|
      tr
        - model_attrs.each do |attr|
          td= record.send(attr)
        - fields.each do |field|
          td= dynabute_value_text(record.dynabute_value(field: field), field)
        td
          = link_to t('.show', :default => t("helpers.links.show")), send("#{model_name}_path", record), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.edit', :default => t("helpers.links.edit")), send("edit_#{model_name}_path", record), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), send("#{model_name}_path", record), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

app/views/users/_form.html.slim
div#dynabute-form
= javascript_pack_tag 'dynabute_form/form'

javascript:
  $('#dynabute-form').data({
    modelId: #{raw @user.id.to_json.html_safe},
    controllerName: #{raw controller_name.to_json.html_safe}
  });

app/views/users/edit.html.slim
- model_class = User
.page-header
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/users/index.html.slim
- model_class = User
.page-header
  h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
  = link_to t('.new', :default => t("helpers.links.new")), new_user_path, :class => 'btn btn-primary'
  = render :partial => "shared/dynabute_value_table", locals: {model_class: model_class, model_attrs: [:name, :created_at], records: @users}

app/views/users/new.html.slim
- model_class = User
.page-header
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/users/show.html.slim
- model_class = User
.page-header
  h1=t '.title', :default => model_class.model_name.human.titleize

p
  strong= model_class.human_attribute_name(:name) + ':'
  br
  = @user.name

= link_to t('.back', :default => t("helpers.links.back")), users_path, :class => 'btn btn-default'
'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(@user), :class => 'btn btn-default'
'
= link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(@user), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'